# 配置文件
# http配置
http: 
  # 服务端口号
  port: 
    - 11067
# https配置
https: 
  # 服务端口号
  port: 
    - 11048
  # 证书路径
  certFile: ''
  # 私钥路径
  keyFile: ''
# 数据库配置
database:
  - 
    key: default
    type: sqlite3
    driver: sqlite3
    host: ./middle.db
    port: 0
    user: ''
    pwd: ''
    instance: ''
    mode: wal
# 常量配置 一个key 一个value 如果有子配置项的话还有sub 之下也是key和value
consts:
  - 
    key: actDataFilenameTemplate
    value: "%s基层党组织组织生活信息录入情况统计表--%s.xlsx"
  -
    key: actDataTableTitleTemplate
    value: "%s下属基层党组织\n组织生活信息录入情况统计表(%s)"
  -
    key: sheetName
    value: 数据导出
  -
    key: rootNo
    value: 033000000018
  -
    # excel文件表格标题的样式
    key: excelStyleTitle
    value: '{
        "alignment":{"horizontal":"center","vertical":"center","wrap_text":true}, 
        "font": {"bold": true, "size":14},
        "border":[{"type":"left","style":1,"color":"000000"},
          {"type":"top","style":1,"color":"000000"},
          {"type":"bottom","style":1,"color":"000000"},
          {"type":"right","style":1,"color":"000000"}]
        }'
  -
    # excel文件表格表头的样式
    key: excelStyleHeader
    value: '{
        "border":[{"type":"left","style":1,"color":"000000"},
          {"type":"top","style":1,"color":"000000"},
          {"type":"bottom","style":1,"color":"000000"},
          {"type":"right","style":1,"color":"000000"}],
        "font": {"bold": true}
        }'
  -
    # excel文件表格单元格的样式
    key: excelStyleCell
    value: '{
        "border":[
          {"type":"left","style":1,"color":"000000"},
          {"type":"top","style":1,"color":"000000"},
          {"type":"bottom","style":1,"color":"000000"},
          {"type":"right","style":1,"color":"000000"}]
        }'
  -
    # excel数据部分第一列下标
    key: excelStartColumnIndex
    value: A
  -
    # excel数据部分最后一列下标
    key: excelEndColumnIndex
    value: I
  -
    # excel导出时间单元格所在列的下标
    key: excelExportTimeColumnIndex
    value: H
  - 
    key: imgRoot
    value: public/upload/pic
  - key: imgRootUrl
    value: /upload/pic/
    sub:
      - 
        key: hotRootUrl
        value: hots/
      - 
        key: videoRootUrl
        value: videos/
includes:
  - config2.yaml
  - config3.yaml